---
- name: Install CRI-O
  ansible.builtin.apt:
    name:
      - cri-o
    state: present

- name: Enable and start CRI-O service
  ansible.builtin.systemd:
    name: cri-o
    enabled: true
    state: started
    daemon_reload: true
