---
- name: Hold kubelet at current version
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm at current version
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl at current version
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold
