---
- name: Install kubelet, kubeadm, kubectl and cri-tools
  ansible.builtin.apt:
    name:
      - "kubelet={{ kubernetes_version }}.*"
      - "kubeadm={{ kubernetes_version }}.*"
      - "kubectl={{ kubernetes_version }}.*"
      - cri-tools
    state: present
