---
- name: Apply AWS Cloud Controller Manager manifests
  ansible.builtin.command:
    cmd: "kubectl apply -k 'github.com/kubernetes/cloud-provider-aws/examples/existing-cluster/base/?ref={{ cloud_provider_aws_version }}'"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: true

- name: Wait for AWS Cloud Controller Manager to be running
  ansible.builtin.command:
    cmd: >
      kubectl wait pod
      --namespace kube-system
      --selector=k8s-app=aws-cloud-controller-manager
      --for=condition=Ready
      --timeout=120s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false
  failed_when: false

- name: Wait for all Antrea agent pods to stabilize after CCM initializes nodes
  ansible.builtin.command:
    cmd: >
      kubectl wait pod
      --namespace kube-system
      --selector=app=antrea,component=antrea-agent
      --for=condition=Ready
      --timeout=45s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false
  failed_when: false
