---
kubernetes_version: "1.30"
cluster_name: "ecommerce-devopsproject-cluster"
pod_subnet: "10.244.0.0/16"
cgroup_driver: "systemd"
crio_socket: "unix:///var/run/crio/crio.sock"
cloud_provider: "external"
kubeconfig_path: "/etc/kubernetes/admin.conf"
terraform_state_bucket: "devopsproject-terraform-state-692430448478"
terraform_state_key: "server/terraform.tfstate"
terraform_state_region: "us-east-1"
ansible_connection: aws_ssm
ansible_aws_ssm_bucket_name: "devopsproject-ecommerce-ansible-ssm"
ansible_aws_ssm_region: "us-east-1"
ansible_aws_ssm_timeout: 60
antrea_version: "v2.1.1"
external_dns_chart_version: "8.3.4"
keda_chart_version: "2.14.3"
prometheus_stack_chart_version: "87.19.1"
cert_manager_chart_version: "v1.17.2"
# grafana_admin_password: injetar via -e grafana_admin_password='...' ou ansible-vault
ecr_registry: "692430448478.dkr.ecr.us-east-1.amazonaws.com"
ecr_pull_secret_name: "dpe-ecr-image-pull-credentials-prod"
gitops_repo_url: "https://github.com/jlui70/devopsproject-ecommerce-gitops"
