---
- name: Install Metrics Server
  ansible.builtin.include_tasks: install.yml

- name: Wait for Metrics Server rollout to complete
  ansible.builtin.command:
    cmd: "kubectl rollout status deployment/metrics-server -n kube-system --timeout=120s"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false
  failed_when: false
