---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags['aws:autoscaling:groupName']
    separator: ""
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
groups:
  control_plane: "'control-plane' in tags.get('aws:autoscaling:groupName', '')"
  workers: "'worker' in tags.get('aws:autoscaling:groupName', '')"
