---
- name: Get installed kubelet semver
  ansible.builtin.shell:
    cmd: kubelet --version | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+'
  register: kubelet_semver_raw
  changed_when: false

- name: Set kubelet_semver fact
  ansible.builtin.set_fact:
    kubelet_semver: "{{ kubelet_semver_raw.stdout | trim }}"

- name: Get IMDSv2 token
  ansible.builtin.command:
    cmd: "curl -sX PUT http://169.254.169.254/latest/api/token -H 'X-aws-ec2-metadata-token-ttl-seconds: 60'"
  register: imds_token
  changed_when: false

- name: Get AWS availability zone
  ansible.builtin.command:
    cmd: "curl -s -H 'X-aws-ec2-metadata-token: {{ imds_token.stdout }}' http://169.254.169.254/latest/meta-data/placement/availability-zone"
  register: cp_aws_az
  changed_when: false

- name: Get AWS instance ID
  ansible.builtin.command:
    cmd: "curl -s -H 'X-aws-ec2-metadata-token: {{ imds_token.stdout }}' http://169.254.169.254/latest/meta-data/instance-id"
  register: cp_aws_instance_id
  changed_when: false

- name: Get AWS private DNS hostname
  ansible.builtin.command:
    cmd: "curl -s -H 'X-aws-ec2-metadata-token: {{ imds_token.stdout }}' http://169.254.169.254/latest/meta-data/local-hostname"
  register: cp_aws_hostname
  changed_when: false

- name: Render kubeadm init configuration template to remote host
  ansible.builtin.template:
    src: kubeadm-init.yml.j2
    dest: /tmp/kubeadm-init.yml
    owner: root
    group: root
    mode: "0640"
